### ISSUE TITLE
Error running emulate utility with greatfet One

### ISSUE THREAD

**Issue by asmitasawhney** [usb-tools/nu-map#10]
I'm using a greatfet one board and UBuntu 18.04 on my host machine. Command used:
`python3 /home/asmita/.local/bin/numap-emulate -P fd:/dev/greatfet-one1-2.2  -C mass_storage`

Its's a different error, but may have a similar root cause as https://github.com/usb-tools/nu-map/issues/4#issue-519984416 

I get the following errors when I run numap-emulate:  

[ERROR ] Got exception while connecting/running device
ERROR:numap:Got exception while connecting/running device
[ERROR ] Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/numap/apps/emulate.py", line 42, in run
    self.dev.run()
  File "/usr/local/lib/python3.6/dist-packages/facedancer-2.9-py3.6.egg/facedancer/USBDevice.py", line 165, in run
    self.scheduler.run()
  File "/usr/local/lib/python3.6/dist-packages/facedancer-2.9-py3.6.egg/facedancer/core.py", line 509, in run
    task()
  File "/usr/local/lib/python3.6/dist-packages/facedancer-2.9-py3.6.egg/facedancer/USBDevice.py", line 83, in <lambda>
    self.scheduler.add_task(lambda : self.maxusb_app.service_irqs())
  File "/usr/local/lib/python3.6/dist-packages/facedancer-2.9-py3.6.egg/facedancer/backends/greatdancer.py", line 765, in service_irqs
    self._handle_setup_events()
  File "/usr/local/lib/python3.6/dist-packages/facedancer-2.9-py3.6.egg/facedancer/backends/greatdancer.py", line 368, in _handle_setup_events
    self._handle_setup_event_on_endpoint(i)
  File "/usr/local/lib/python3.6/dist-packages/facedancer-2.9-py3.6.egg/facedancer/backends/greatdancer.py", line 402, in _handle_setup_event_on_endpoint
    self.connected_device.handle_request(request)
  File "/usr/local/lib/python3.6/dist-packages/facedancer-2.9-py3.6.egg/facedancer/USBDevice.py", line 235, in handle_request
    handler_entity = recipient.device_class
AttributeError: 'USBMassStorageInterface' object has no attribute 'device_class'

ERROR:numap:Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/numap/apps/emulate.py", line 42, in run
    self.dev.run()
  File "/usr/local/lib/python3.6/dist-packages/facedancer-2.9-py3.6.egg/facedancer/USBDevice.py", line 165, in run
    self.scheduler.run()
  File "/usr/local/lib/python3.6/dist-packages/facedancer-2.9-py3.6.egg/facedancer/core.py", line 509, in run
    task()
  File "/usr/local/lib/python3.6/dist-packages/facedancer-2.9-py3.6.egg/facedancer/USBDevice.py", line 83, in <lambda>
    self.scheduler.add_task(lambda : self.maxusb_app.service_irqs())
  File "/usr/local/lib/python3.6/dist-packages/facedancer-2.9-py3.6.egg/facedancer/backends/greatdancer.py", line 765, in service_irqs
    self._handle_setup_events()
  File "/usr/local/lib/python3.6/dist-packages/facedancer-2.9-py3.6.egg/facedancer/backends/greatdancer.py", line 368, in _handle_setup_events
    self._handle_setup_event_on_endpoint(i)
  File "/usr/local/lib/python3.6/dist-packages/facedancer-2.9-py3.6.egg/facedancer/backends/greatdancer.py", line 402, in _handle_setup_event_on_endpoint
    self.connected_device.handle_request(request)
  File "/usr/local/lib/python3.6/dist-packages/facedancer-2.9-py3.6.egg/facedancer/USBDevice.py", line 235, in handle_request
    handler_entity = recipient.device_class
AttributeError: 'USBMassStorageInterface' object has no attribute 'device_class'

**Comment by straithe** [comment]
Are you still experiencing this issue, @asmitasawhney?

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
