### ISSUE TITLE
numap-stages  -C ftdi -s=stages.ftdi fails 

### ISSUE THREAD

**Issue by keesj** [usb-tools/nu-map#14]
There is more python3 goodness when running numap-stages  -C ftdi -s=stages.ftdi fails 

```
ERROR:numap:Traceback (most recent call last):
  File "/home/pentest/projects/nu-map/numap/apps/emulate.py", line 42, in run
    self.dev.run()
  File "/home/pentest/projects/Facedancer/facedancer/USBDevice.py", line 165, in run
    self.scheduler.run()
  File "/home/pentest/projects/Facedancer/facedancer/core.py", line 509, in run
    task()
  File "/home/pentest/projects/Facedancer/facedancer/USBDevice.py", line 83, in <lambda>
    self.scheduler.add_task(lambda : self.maxusb_app.service_irqs())
  File "/home/pentest/projects/Facedancer/facedancer/backends/greatdancer.py", line 765, in service_irqs
    self._handle_setup_events()
  File "/home/pentest/projects/Facedancer/facedancer/backends/greatdancer.py", line 368, in _handle_setup_events
    self._handle_setup_event_on_endpoint(i)
  File "/home/pentest/projects/Facedancer/facedancer/backends/greatdancer.py", line 402, in _handle_setup_event_on_endpoint
    self.connected_device.handle_request(request)
  File "/home/pentest/projects/Facedancer/facedancer/USBDevice.py", line 251, in handle_request
    handler(req)
  File "/home/pentest/projects/Facedancer/facedancer/USBDevice.py", line 326, in handle_get_descriptor_request
    response = response(dindex)
  File "/home/pentest/projects/Facedancer/facedancer/USBDevice.py", line 53, in <lambda>
    self.descriptors[USB.desc_type_device] = lambda _ : self.get_descriptor()
  File "/home/pentest/projects/nu-map/numap/fuzz/helpers.py", line 63, in wrapper
    log_stage(stage)
  File "/home/pentest/projects/nu-map/numap/fuzz/helpers.py", line 42, in log_stage
    stage_logger.log_stage(stage)
  File "/home/pentest/projects/nu-map/numap/fuzz/helpers.py", line 25, in log_stage
    self.fd.write(stage + '\n')
TypeError: a bytes-like object is required, not 'str'

```

**Comment by straithe** [comment]
Are you looking for support with this issue, or were you just looking to make us aware of this issue?

**Comment by keesj** [comment]
Hi @straithe, I am looking into getting this project into a better state and started logging issue.
At one time I felt more like the project was more foobar then I could handle at that point. I would like to see the project at least mostly working on python3 before I feel we can try fuzzing with it again.

**Comment by straithe** [comment]
I will let my developers know, thank you! If you do put in any PRs I will try to fast track a review of them.
